### ISSUE TITLE
Forge version requests some fabric api

### ISSUE THREAD

**Issue by zecheki** [Skidamek/AutoModpack#174]
### Bug description

The Forge server is terminated with an exception related to fabric api when starting.
I tried on other forge/automodpack version, but I can't find any valid set.

### Steps to reproduce

1. Install forge server
2. Install the mod
3. Execute run.bat

### Relevant logs

[11:21:03] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.1.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[11:21:03] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 20.0.2 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[11:21:03] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[11:21:03] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/Minecraft/Curseforge/Instances/OMSCTE2Server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[11:21:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\Minecraft\Curseforge\Instances\OMSCTE2Server\libraries\net\minecraftforge\fmlcore\1.20.1-47.1.3\fmlcore-1.20.1-47.1.3.jar is missing mods.toml file
[11:21:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\Minecraft\Curseforge\Instances\OMSCTE2Server\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.1.3\javafmllanguage-1.20.1-47.1.3.jar is missing mods.toml file
[11:21:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\Minecraft\Curseforge\Instances\OMSCTE2Server\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.1.3\lowcodelanguage-1.20.1-47.1.3.jar is missing mods.toml file
[11:21:04] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file E:\Minecraft\Curseforge\Instances\OMSCTE2Server\libraries\net\minecraftforge\mclanguage\1.20.1-47.1.3\mclanguage-1.20.1-47.1.3.jar is missing mods.toml file
[11:21:04] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File:
[11:21:04] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: E:\Minecraft\Curseforge\Instances\OMSCTE2Server\mods\resourcefullib-forge-1.20.1-2.1.11.jar
[11:21:04] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 46 dependencies adding them to mods collection[11:21:04] [main/INFO] [PreloadingTricks/LanguageProvider/]: [PreloadingTricks/LanguageProvider] Loading settingdust.preloadingtricks.fabric.FabricLanguageProviderCallback
[11:21:04] [main/INFO] [PreloadingTricks/LanguageProvider/]: [PreloadingTricks/LanguageProvider] Loading settingdust.preloadingtricks.quilt.QuiltLanguageProviderCallback
[11:21:04] [main/INFO] [PreloadingTricks/LanguageProvider/]: [PreloadingTricks/LanguageProvider] Loading settingdust.preloadingtricks.forge.ForgeLanguageProviderCallback
[11:21:04] [main/INFO] [or.gr.gm.ma.MappingsProvider/]: Starting runtime mappings setup...
[11:21:04] [main/INFO] [or.gr.gm.in.lo.ModLocatorInjector/]: Injecting ScriptModLocator candidates...
[11:21:04] [main/INFO] [or.gr.gm.sc.ScriptModLocator/]: Injected Jimfs file system
[11:21:04] [main/INFO] [or.gr.gm.sc.ScriptModLocator/]: Skipped loading script mods from directory E:\Minecraft\Curseforge\Instances\OMSCTE2Server\mods\scripts as it did not exist.
[11:21:04] [main/INFO] [or.gr.gm.in.lo.ModLocatorInjector/]: Injected ScriptModLocator mod candidates. Found 0 valid mod candidates and 0 broken mod files.
[11:21:04] [main/INFO] [PreloadingTricks/ModSetup/]: [PreloadingTricks/ModSetup] Loading pl.skidam.automodpack_core.Preload
[11:21:04] [main/INFO] [AutoModpack/]: Prelaunching AutoModpack...
[11:21:04] [main/INFO] [AutoModpack/]: Loaded config! took 8ms
[11:21:04] [main/INFO] [AutoModpack/]: Checking if AutoModpack is up-to-date...
[11:21:05] [main/INFO] [AutoModpack/]: Didn't find any updates for AutoModpack! You are on the latest version: 3.5.2
[11:21:05] [main/INFO] [AutoModpack/]: AutoModpack prelaunched! took 471ms
[11:21:05] [GML Mappings Thread/INFO] [or.gr.gm.ma.MappingsProvider/]: Loaded runtime mappings in 552ms
[11:21:05] [GML Mappings Thread/INFO] [or.gr.gm.ma.MappingsProvider/]: Finished runtime mappings setup.
Exception in thread "main" java.lang.module.ResolutionException: Modules creativecore and net.fabricmc.loader export package net.fabricmc.api to module bettertridents
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

### Minecraft & Mod Loader versions

1.20.1 forge 47.1.3

### Operating system

Windows 11

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by zecheki** [comment]
I add the missing information.
The server works well without the automodpack.

**Comment by zecheki** [comment]
I solved this problem. The cause was "CreativeCore" mod ( https://www.curseforge.com/minecraft/mc-mods/creativecore ).
But I don't know why it works like this.
