### ISSUE TITLE
[FORGE] CreativeCore and Rubidium Incompatibility

### ISSUE THREAD

**Issue by haruww** [Skidamek/AutoModpack#177]
### Bug description

crashes when using 

https://modrinth.com/mod/creativecore

### Steps to reproduce

1. open minecraft

### Minecraft & Mod Loader versions

1.20.1 NeoForged 47.1.79

### Operating system

Windows10

### AutoModpack version

3.5.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by haruww** [comment]
[14:35:42.462] [main/INFO] [AutoModpack/]: You are using pre-released or beta version of AutoModpack: 3.5.3-SHAPSHOT latest stable version is: 3.5.2
[14:35:42.519] [main/INFO] [AutoModpack/]: AutoModpack prelaunched! took 542ms
Exception in thread "main" java.lang.module.ResolutionException: Modules net.fabricmc.loader and creativecore export package net.fabricmc.api to module dagger
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by Skidamek** [comment]
Currently automodpack uses FFAPI in forge version, which is incompatible with creativecore. https://github.com/Sinytra/ForgifiedFabricAPI/issues/37

**Comment by haruww** [comment]
15:03:38.296
game
[15:03:38.295] [main/INFO] [AutoModpack/]: AutoModpack prelaunched! took 750ms
15:03:39.749
game
Exception in thread "main" java.lang.module.ResolutionException: Modules net.fabricmc.loader and rubidium export package net.fabricmc.loader.util.version to module voicechat

Is this some kinda same issue like creativecore?

**Comment by Skidamek** [comment]
Yep that's the same issue they bundles part of fabric API into the mod in the same wrong incompatible for us way. Try  [Embeddium](https://modrinth.com/mod/embeddium)

**Comment by haruww** [comment]
hmm Embeddium does not seem work properly with my mod sets its compatibility is worse than Rubidium
I guess I can't use your mod sadly

**Comment by MrKashew** [comment]
@Skidamek Seems there is a solution/workaround on FFAPI for this, I've tried the same for Automodpack but it still crashes, any thoughts?
https://github.com/Sinytra/ForgifiedFabricAPI/issues/37#issuecomment-1751684746

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
