### ISSUE TITLE
impatibility with creative core

### ISSUE THREAD

**Issue by dasdwavbc** [Skidamek/AutoModpack#205]
### Bug description

Exception in thread "main" java.lang.module.ResolutionException: Modules net.fabricmc.loader and creativecore export package net.fabricmc.api to module midnightbutton

at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)

at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)

at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)

at java.base/java.lang.module.Resolver.finish(Resolver.java:380)

at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)

at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)

at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

at com.mohistmc.MohistMCStart.main(MohistMCStart.java:104)

### Steps to reproduce

load mod with creative core(another mod)
start game
crash

### Expected behavior

game should boot normally

### Minecraft & Mod Loader versions

1.20.1 forge

### Operating system

win10

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
#177 duplicate
