### ISSUE TITLE
Failed to download fabric 1.20.1

### ISSUE THREAD

**Issue by archenovalis** [Skidamek/AutoModpack#242]
### Bug description

Client receives modpack-content.json but cannot download any other files from the server. Client is able to download some files from modrinth.

### Steps to reproduce

start server
start client

### Expected behavior

download files from server

### Actual behavior

failed to download any mods or configs from the server

### Relevant logs

```
[15:03:08] [AutoModpackDownload-1/INFO]: Downloading automodpack\modpacks\valowank\mods\Soaring-Structures-2-1.20.1-2.5.1-FABRIC.jar from http://192.168.56.1:29146/automodpack/9e6729aec9218c6555b3118dd8776a8bc34f1e9e
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: java.io.FileNotFoundException: http://192.168.56.1:29146/automodpack/9e6729aec9218c6555b3118dd8776a8bc34f1e9e
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2015)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.utils.DownloadManager.downloadFile(DownloadManager.java:168)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.utils.DownloadManager.downloadTask(DownloadManager.java:67)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.utils.DownloadManager.lambda$downloadNext$0(DownloadManager.java:134)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:03:08] [AutoModpackDownload-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:842)
```

### Minecraft & Mod Loader versions

1.20.1 fabric 0.15.11

### Minecraft launcher

Prism

### Operating system

win10

### AutoModpack version

4.0.0beta1

### Other information
file location on server is correct:
![image](https://github.com/Skidamek/AutoModpack/assets/141416512/bb5a17f0-0d25-49b0-8d5d-f798cbe8ea19)

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by archenovalis** [comment]
hash is correct:
![image](https://github.com/Skidamek/AutoModpack/assets/141416512/b235a8fd-ad4e-4995-9b6f-82431535c242)

**Comment by archenovalis** [comment]
server correctly updates client's content file and receives correct hash request:
![image](https://github.com/Skidamek/AutoModpack/assets/141416512/97fea0b6-db4d-40a9-a164-728b003f4007)

**Comment by Skidamek** [comment]
Try latest build from GitHub actions it might have been already fixed in dev

**Comment by Skidamek** [comment]
https://github.com/Skidamek/AutoModpack/actions/workflows/gradle.yml

**Comment by Skidamek** [comment]
And could you send your automodpack server config file?

**Comment by archenovalis** [comment]
found the issue.

server didn't generate the content.json so it had not generated the hash map. using the server to generate the content.json fixed the issue

**Comment by Skidamek** [comment]
Why did it not generate modpack? Was `generateModpackOnStart` disabled?

**Comment by Skidamek** [comment]
Should work now i guess, let me know if you able to reproduce it on beta 2
