### ISSUE TITLE
NullPointerException after downloading mods from the server

### ISSUE THREAD

**Issue by draganczukp** [Skidamek/AutoModpack#260]
### Bug description

Mod download progresses correctly, then a red error shows up. Attempting to reconnect to server shows an error about missing registries, persisting even after restarting

Here are the logs

MC 1.21
Fabric 0.16.0

### Steps to reproduce

1. Install mod on server
2. Join server
3. Click "Download"
4. Wait for it to finish
5. It crashes

### Expected behavior

Mods download and install, then connect to server

### Actual behavior

NullPointerException

### Relevant logs

```
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonObject()" because the return value of "com.google.gson.JsonObject.get(String)" is null
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_core.utils.FileInspection.getModDependencies(FileInspection.java:217)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.loader.LoaderManager.getMod(LoaderManager.java:105)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.client.ModpackUtils.lambda$getDupeMods$2(ModpackUtils.java:142)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:622)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:631)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:637)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:642)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.client.ModpackUtils.getDupeMods(ModpackUtils.java:142)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.client.ModpackUpdater.finishModpackUpdate(ModpackUpdater.java:401)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack_loader_core.client.ModpackUpdater.ModpackUpdaterMain(ModpackUpdater.java:332)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at pl.skidam.automodpack.client.ui.DangerScreen.lambda$init$1(DangerScreen.java:44)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[15:08:18] [Worker-Main-11/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

### Minecraft & Mod Loader versions

1.21 Fabric 0.16.0

### Minecraft launcher

Prism

### Operating system

Linux

### AutoModpack version

4.0.0-beta11

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by draganczukp** [comment]
Seems to be fixed. Thanks

**Comment by Skidamek** [comment]
Published fix in beta 12
