### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by lanwoodall423** [Skidamek/AutoModpack#261]
### Bug description

UnsupportedClassVersionError: pl/skidam/automodpack_loader_core/FabricLanguageAdapter has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

### Steps to reproduce

Launch

### Expected behavior

Load

### Actual behavior

UnsupportedClassVersionError: pl/skidam/automodpack_loader_core/FabricLanguageAdapter has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

### Relevant logs

UnsupportedClassVersionError: pl/skidam/automodpack_loader_core/FabricLanguageAdapter has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

at java.base/java.lang.ClassLoader.defineClass 1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd (KnotClassLoader.java:160) at net.fabricmc.loader.impl.launch.knot.
KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:467)
at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters (FabricLoaderImpl.java:473) at net.fabricmc.loader.impl.FabricLoaderImpl. finishModLoading (FabricLoaderImpl.java:352)
at net.fabricmc.loader.impl.FabricLoaderImpl.freeze (FabricLoaderImpl.java:115)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.15.11

### Minecraft launcher

Curseforge

### Operating system

Windows 10

### AutoModpack version

4.0.0 Beta 12

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Whoops, forgot about that....
Please use beta 11 or use java 21 instead of 17

**Comment by Skidamek** [comment]
Please try dev build from GitHub actions https://github.com/Skidamek/AutoModpack/actions/runs/10236272668#artifacts

**Comment by Whitebrim** [comment]
> Please try dev build from GitHub actions https://github.com/Skidamek/AutoModpack/actions/runs/10236272668#artifacts

It works!
