### ISSUE TITLE
Speedmeter is Freezing on Downloading Modpack. Mod Works, Only Display Issue (Fabrich 1.21.1 / 016.9) [File Issues Added also]

### ISSUE THREAD

**Issue by suerion** [Skidamek/AutoModpack#302]
### Bug description

Hey as Tested on Beta 20, Speedmeter is Freezing Random on Downloading an Modpack. The files would be finishing on Downloading. It is only an Display Issue

### Steps to reproduce

Add Automodpack Beta 20 to Server.
Try to Join on Server with Client, 
Download Modpack.

### Relevant logs

```
[17:06:52] [Worker-Main-2/ERROR]: Caught exception in thread Thread[#54,Worker-Main-2,5,main]
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.TreeMap.get(Object)" is null
at knot/pl.skidam.automodpack_loader_core.utils.SpeedMeter.getCurrentSpeedInBytes(SpeedMeter.java:39) ~[automodpack-mc1.21.1-fabric-4.0.0-beta20.jar:?]
at knot/pl.skidam.automodpack_loader_core.utils.SpeedMeter.getETAInSeconds(SpeedMeter.java:52) ~[automodpack-mc1.21.1-fabric-4.0.0-beta20.jar:?]
at knot/pl.skidam.automodpack.client.ui.DownloadScreen.lambda$init$0(DownloadScreen.java:72) ~[automodpack-4.0.0-beta20-77b41d0aae131a50.jar:?]
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) [?:?]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

Error on Downloading on Server ->
```[17:08:26 ERROR] [Netty Acceptor IO Thread]: [AutoModpack] Error writing to channel: null path: C:\Users\Bremo\Desktop\Testserver\mods\supplementaries-1.21-3.0.23-beta-fabric.jar.disabled io.netty.channel.StacklessClosedChannelException```

File Issue on Client ->
```
[17:11:03] [AutoModpackDownload-2/INFO]: Downloading customsplashscreen-2.2.0.jar.disabled - [http://x:25570/automodpack/bb79f8974e619e077d60a6bdffe389913b84defd]
[17:11:03] [AutoModpackDownload-2/WARN]: Error while downloading file - automodpack\modpacks\Hardcore Adventure and Furniture Server Modpack by Suerion\mods\customsplashscreen-2.2.0.jar.disabled - java.nio.file.FileAlreadyExistsException: automodpack\modpacks\Hardcore Adventure and Furniture Server Modpack by Suerion\mods\customsplashscreen-2.2.0.jar.disabled - [java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87), java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103), java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108), java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234), java.base/java.nio.file.Files.newByteChannel(Files.java:379), java.base/java.nio.file.Files.createFile(Files.java:657), knot//pl.skidam.automodpack_loader_core.utils.DownloadManager.downloadFile(DownloadManager.java:146), knot//pl.skidam.automodpack_loader_core.utils.DownloadManager.downloadTask(DownloadManager.java:56), knot//pl.skidam.automodpack_loader_core.utils.DownloadManager.lambda$downloadNext$0(DownloadManager.java:121), java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base/java.lang.Thread.run(Thread.java:1583)]
[17:11:03] [AutoModpackDownload-2/WARN]: Download of customsplashscreen-2.2.0.jar.disabled failed, retrying!
[17:11:03] [AutoModpackDownload-3/INFO]: Downloading customsplashscreen-2.2.0.jar.disabled - [http://x:25570/automodpack/bb79f8974e619e077d60a6bdffe389913b84defd]
[17:11:03] [AutoModpackDownload-1/INFO]: Successfully downloaded customsplashscreen-2.2.0.jar.disabled from http://x:25570/automodpack/bb79f8974e619e077d60a6bdffe389913b84defd
[17:11:03] [AutoModpackDownload-3/INFO]: Successfully downloaded customsplashscreen-2.2.0.jar.disabled from http:/x:25570/automodpack/bb79f8974e619e077d60a6bdffe389913b84defd
[17:11:03] [main/INFO]: Finished downloading files in 373ms
```

### Minecraft & Mod Loader versions

Fabric 1.21.1 on 0.16.9

### Minecraft launcher

Curseforge Vanilla Launcher

### Operating system

Windows 11

### AutoModpack version

beta 20

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
How the heck is that possible? Windows lol...
```
Error while downloading file - automodpack\modpacks\Hardcore Adventure and Furniture Server Modpack by Suerion\mods\customsplashscreen-2.2.0.jar.disabled - 
java.nio.file.FileAlreadyExistsException: automodpack\modpacks\Hardcore Adventure and Furniture Server Modpack by Suerion\mods\customsplashscreen-2.2.0.jar.disabled - 
[java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87),
 java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103),
 java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108),
 java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234),
 java.base/java.nio.file.Files.newByteChannel(Files.java:379),
 java.base/java.nio.file.Files.createFile(Files.java:657),
 knot//pl.skidam.automodpack_loader_core.utils.DownloadManager.downloadFile(DownloadManager.java:146)
```
DownloadManager.java:
```
145: if (!Files.exists(outFile)) {
146: 	Files.createFile(outFile);
147: }
```

**Comment by Skidamek** [comment]
Please try to reproduce any of the issues. I tried to address them all. [build](https://github.com/Skidamek/AutoModpack/actions/runs/11990351155)

**Comment by suerion** [comment]
@Skidamek 

Runs nice on download but stop on latest file, will not finish the download on first download, and on the log, there are Some timeout warnings...
Need to stop download
On second trying download it does finish.

https://mclo.gs/beLVp6p

![image](https://github.com/user-attachments/assets/c93f82f3-3dbe-4dd9-b063-c3573d533b49)
![image](https://github.com/user-attachments/assets/d5acf8f4-199f-4ba6-a890-b1ebfffa3438)

**Comment by Skidamek** [comment]
could you try this [build](https://github.com/Skidamek/AutoModpack/actions/runs/12037223143)
what i want to achive is to make screen work properly without it being freezed, but we dont really care about timeouts thats just nature of internet

**Comment by suerion** [comment]
Here the log on Clean client ;)

https://mclo.gs/g6FAEpv

**Comment by Skidamek** [comment]
Looks good, how was the screen? Was download speed counter roughly correct and smooth?

**Comment by suerion** [comment]
Was really smooth yet :)

**Comment by Skidamek** [comment]
thanks closing, beta 21 released
