### ISSUE TITLE
Console bug

### ISSUE THREAD

**Issue by LEEEEEEEN** [Skidamek/AutoModpack#310]
### Bug description

when i want to start server, i get error to my console

### Steps to reproduce

1. load automodpack automodpack-mc1.18.2-forge-4.0.0-beta21    or   automodpack-mc1.18.2-forge-4.0.0-beta22
2. start server with version 1.18.2-40.2.0 and jdk 17
3. get error in console

### Expected behavior

quiet server startup

### Actual behavior

stopping server

### Relevant logs

[19:12:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/fmlcore/1.18.2-40.2.0/fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[19:12:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/javafmllanguage/1.18.2-40.2.0/javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[19:12:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/lowcodelanguage/1.18.2-40.2.0/lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[19:12:21] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/container/libraries/net/minecraftforge/mclanguage/1.18.2-40.2.0/mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
Exception in thread "main" java.lang.RuntimeException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/container/mods/automodpack-mc1.18.2-forge-4.0.0-beta21.jar%2339/automodpack-mod.jar
        at LAYER SERVICE/automodpack.mc1._18._2.forge.beta21@4.0.0-beta21/pl.skidam.automodpack_loader_core.LazyModLocator.scanMods(LazyModLocator.java:26)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:98)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /home/container/mods/automodpack-mc1.18.2-forge-4.0.0-beta21.jar%2339/automodpack-mod.jar
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:59)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:52)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:75)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.0/net.minecraftforge.fml.loading.moddiscovery.AbstractModLocator.createMod(AbstractModLocator.java:35)
        at LAYER SERVICE/automodpack.mc1._18._2.forge.beta21@4.0.0-beta21/pl.skidam.automodpack_loader_core.LazyModLocator.getMainMod(LazyModLocator.java:54)
        at LAYER SERVICE/automodpack.mc1._18._2.forge.beta21@4.0.0-beta21/pl.skidam.automodpack_loader_core.LazyModLocator.scanMods(LazyModLocator.java:24)
        ... 21 more
Caused by: java.nio.file.NoSuchFileException: /home/container/mods/automodpack-mc1.18.2-forge-4.0.0-beta21.jar%2339/automodpack-mod.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.pathfs.PathFileSystem.newByteChannel(PathFileSystem.java:146)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.pathfs.PathFileSystemProvider.newByteChannel(PathFileSystemProvider.java:123)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.pathfs.PathFileSystem.newByteChannel(PathFileSystem.java:138)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.pathfs.PathFileSystemProvider.newByteChannel(PathFileSystemProvider.java:123)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:177)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:475)
        at cpw.mods.securejarhandler@1.0.3/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:57)
        ... 37 more

### Minecraft & Mod Loader versions

1.18.2-40.2.0

### Operating system

Windows 10

### AutoModpack version

automodpack-mc1.18.2-forge-4.0.0-beta22 or  automodpack-mc1.18.2-forge-4.0.0-beta21

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by LEEEEEEEN** [comment]
i renamed downloaded file, and everything started working

**Comment by Skidamek** [comment]
Update forge, it requires securejarhandler 1.0.8 or higher so `forge 40.2.3` and up
