### ISSUE TITLE
A crash error on start using only fabric API and Automodpack 1.19

### ISSUE THREAD

**Issue by PedalHat29861** [Skidamek/AutoModpack#36]
With both mods (Fabric API installed manually)

Error log:
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
    at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
    ... 2 more
Caused by: java.lang.NumberFormatException: For input string: "5,8"
    at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
    at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.base/java.lang.Float.parseFloat(Float.java:476)
    at pl.skidam.automodpack.utils.Download.Download(Download.java:64)
    at pl.skidam.automodpack.client.modpack.TrashMod.<init>(TrashMod.java:24)
    at pl.skidam.automodpack.PreLoad.onPreLaunch(PreLoad.java:50)
    at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
    ... 4 more

And only with AutoModpack:

A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
	at pl.skidam.automodpack.utils.SetupFiles.client(SetupFiles.java:100)
	at pl.skidam.automodpack.utils.SetupFiles.<init>(SetupFiles.java:28)
	at pl.skidam.automodpack.PreLoad.onPreLaunch(PreLoad.java:42)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:142)
	at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:120)
	at pl.skidam.automodpack.utils.UnZipper.progressBarSetup(UnZipper.java:114)
	at pl.skidam.automodpack.utils.UnZipper.<init>(UnZipper.java:19)
	at pl.skidam.automodpack.utils.SetupFiles.client(SetupFiles.java:98)
	... 7 more

**Comment by Skidamek** [comment]
Can you try this? https://github.com/Skidamek/AutoModpack/suites/7434631538/artifacts/303850395

**Comment by Skidamek** [comment]
fixed in 2.2.4
