### ISSUE TITLE
modpackHostIpForLocalPlayers reporting null, preventing client connections

### ISSUE THREAD

**Issue by Toon2400** [Skidamek/AutoModpack#59]
[15:49:44] [Server thread/WARN]: Failed to handle packet for /myhomeip:63043
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "pl.skidam.automodpack.server.HostModpack.modpackHostIpForLocalPlayers" is null
	at pl.skidam.automodpack.AutoModpackServer.onLoginStart(AutoModpackServer.java:98) ~[AutoModpack-1.18.x.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerLoginConnectionEvents.lambda$static$2(ServerLoginConnectionEvents.java:51) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.queryTick(ServerLoginNetworkAddon.java:81) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?] 
	at net.minecraft.class_3248.redirect$zkd000$handlePlayerJoin(class_3248.java:1062) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bkm000$onTickServer(MinecraftServer.java:9305) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

I would assume that I wouldn't want 2 servers trying to host the modpack download on the same port/ip so i turned it off and told it to point to the same server's ip that the other one reports it is hosting on
#Configuration file for AutoModpack
#Sun Sep 04 06:14:40 UTC 2022
generate_modpack_on_launch=false
host_thread_count=2
sync_mods=false
danger_screen=false
only_optional_modpack=false
host_port=30037
modpack_host=false
external_modpack_host=http\://192.9.243.44\:30037/modpack
delete_modpack_button=false
host_external_ip_for_local_players=http\://127.0.1.1\:30037/modpack
check_updates_button=false
host_external_ip=http\://192.9.243.44\:30037/modpack
auto_exclude_server_side_mods=false

the main server tells me
[10:08:44] [ForkJoinPool.commonPool-worker-1/INFO]: Modpack host started at http://192.9.243.44:30037/modpack and http://127.0.1.1:30037/modpack for local players.
when it starts the pack host

**Comment by Skidamek** [comment]
try setup config like that

#Configuration file for AutoModpack
#Sun Sep 04 06:14:40 UTC 2022
generate_modpack_on_launch=false
host_thread_count=2
sync_mods=false
danger_screen=false
only_optional_modpack=false
host_port=30037
modpack_host=false
external_modpack_host=
delete_modpack_button=false
host_external_ip_for_local_players=
check_updates_button=false
host_external_ip=192.9.243.44
auto_exclude_server_side_mods=false

**Comment by Toon2400** [comment]
same error
[11:01:46] [Server thread/WARN]: Failed to handle packet for /myhomeip:60845
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "pl.skidam.automodpack.server.HostModpack.modpackHostIpForLocalPlayers" is null
	at pl.skidam.automodpack.AutoModpackServer.onLoginStart(AutoModpackServer.java:98) ~[AutoModpack-1.18.x.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerLoginConnectionEvents.lambda$static$2(ServerLoginConnectionEvents.java:51) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.queryTick(ServerLoginNetworkAddon.java:81) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.minecraft.class_3248.redirect$zkd000$handlePlayerJoin(class_3248.java:1062) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bla000$onTickServer(MinecraftServer.java:9305) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

https://puu.sh/JjCY9/eebd3527fb.png

**Comment by Skidamek** [comment]
hmm try that one

#Configuration file for AutoModpack
#Sun Sep 04 06:14:40 UTC 2022
generate_modpack_on_launch=false
host_thread_count=2
sync_mods=false
danger_screen=false
only_optional_modpack=false
host_port=30037
modpack_host=false
external_modpack_host=
delete_modpack_button=false
host_external_ip_for_local_players=127.0.1.1
check_updates_button=false
host_external_ip=192.9.243.44
auto_exclude_server_side_mods=false

**Comment by Toon2400** [comment]
still reports
[11:42:40] [Server thread/WARN]: Failed to handle packet for /stillmyhomeip:61473
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "pl.skidam.automodpack.server.HostModpack.modpackHostIpForLocalPlayers" is null
	at pl.skidam.automodpack.AutoModpackServer.onLoginStart(AutoModpackServer.java:98) ~[AutoModpack-1.18.x.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerLoginConnectionEvents.lambda$static$2(ServerLoginConnectionEvents.java:51) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon.queryTick(ServerLoginNetworkAddon.java:81) ~[fabric-networking-api-v1-1.0.23+2d30af4b60-4536c950854534c8.jar:?]
	at net.minecraft.class_3248.redirect$zkd000$handlePlayerJoin(class_3248.java:1062) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bla000$onTickServer(MinecraftServer.java:9305) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by SinisterEmber** [comment]
Can we see the most recent version of the config? 

Is it set as: 
#Configuration file for AutoModpack
#Sun Sep 04 06:14:40 UTC 2022
generate_modpack_on_launch=false
host_thread_count=2
sync_mods=false
danger_screen=false
only_optional_modpack=false
host_port=30037
modpack_host=false
external_modpack_host=192.9.243.44
delete_modpack_button=false
host_external_ip_for_local_players=127.0.1.1
check_updates_button=false
host_external_ip=192.9.243.44
auto_exclude_server_side_mods=false

or like as you only need the ip address, you don't need to include the port or the subdomain on the config unless you are pointing to an external hosting service on with external_modpack_host like google drive. 

#Configuration file for AutoModpack
#Sun Sep 04 06:14:40 UTC 2022
generate_modpack_on_launch=false
host_thread_count=2
sync_mods=false
danger_screen=false
only_optional_modpack=false
host_port=30037
modpack_host=false
external_modpack_host=http://192.9.243.44:30037/modpack
delete_modpack_button=false
host_external_ip_for_local_players=http://127.0.1.1:30037/modpack
check_updates_button=false
host_external_ip=http://192.9.243.44:30037/modpack
auto_exclude_server_side_mods=false

**Comment by Skidamek** [comment]
Should be fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
