### ISSUE TITLE
[3.0.0] Does not install Fabric Api on startup

### ISSUE THREAD

**Issue by Eatham532** [Skidamek/AutoModpack#83]
**Describe the bug**
When your game starts with AutoModpack installed, the mod installs the Fabric Api from Modrinth. This fails with the following in the log:

```
[11:10:50] [main/INFO]: Prelaunching AutoModpack...
[11:10:51] [main/INFO]: Loaded config in 386ms
[11:10:51] [main/INFO]: Checking if AutoModpack is up-to-date...
[11:10:53] [main/WARN]: Can't find mod for your client, tried link https://api.modrinth.com/v2/project/k68glP2e/version?loaders=[%22fabric%22]&game_versions=[%221.19.3%22]
[11:10:53] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.1]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "automodpack.modrinthAPIversion" is null
	at pl.skidam.automodpack.logic.SelfUpdater.<init>(SelfUpdater.java:57) ~[automodpack-fabric-3.0.0.jar:?]
	at pl.skidam.automodpack.AutoModpack.onPreInitialize(AutoModpack.java:100) ~[automodpack-fabric-3.0.0.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy21.onPreLaunch(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.13.jar:?]
	... 4 more
```

**To Reproduce**
1. Open Minecraft with only AutoModpack Installed

**Expected behavior**
The mod to install FabricApi

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - 3.0.0 Minecraft 1.19.3

**Comment by Eatham532** [comment]
Closed because I misread the logs.
